name: Upload pdf file
on: [push]
jobs:
  upload_pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: ronitCV.tex
        extra_fonts: ./overpass.ttf
#        latexmk_use_xelatex: true

    - uses: actions/upload-artifact@v4
      with:
        name: ronitCV
        path: ronitCV.pdf

    - name: Generate release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ronitCV.pdf
